# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='chatservice',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nchat.proto\x12\x0b\x63hatservice\"\x07\n\x05\x45mpty\"\x18\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\"$\n\x0fListofUsernames\x12\x11\n\tusernames\x18\x01 \x03(\t\"\x1c\n\x08Wildcard\x12\x10\n\x08wildcard\x18\x01 \x01(\t\"H\n\x0b\x43hatMessage\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x16\n\x0erecip_username\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x1f\n\rMessageStatus\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32\xda\x03\n\nChatServer\x12\x35\n\rCreateAccount\x12\x11.chatservice.User\x1a\x11.chatservice.User\x12\x35\n\rDeleteAccount\x12\x11.chatservice.User\x1a\x11.chatservice.User\x12\x43\n\x0cListAccounts\x12\x15.chatservice.Wildcard\x1a\x1c.chatservice.ListofUsernames\x12;\n\nChatStream\x12\x11.chatservice.User\x1a\x18.chatservice.ChatMessage0\x01\x12\x43\n\x0bSendMessage\x12\x18.chatservice.ChatMessage\x1a\x1a.chatservice.MessageStatus\x12\x38\n\x0f\x44\x65liverMessages\x12\x11.chatservice.User\x1a\x12.chatservice.Empty\x12-\n\x05Login\x12\x11.chatservice.User\x1a\x11.chatservice.User\x12.\n\x06Logout\x12\x11.chatservice.User\x1a\x11.chatservice.Userb\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='chatservice.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=34,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='chatservice.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='chatservice.User.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=60,
)


_LISTOFUSERNAMES = _descriptor.Descriptor(
  name='ListofUsernames',
  full_name='chatservice.ListofUsernames',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='usernames', full_name='chatservice.ListofUsernames.usernames', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=98,
)


_WILDCARD = _descriptor.Descriptor(
  name='Wildcard',
  full_name='chatservice.Wildcard',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wildcard', full_name='chatservice.Wildcard.wildcard', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=128,
)


_CHATMESSAGE = _descriptor.Descriptor(
  name='ChatMessage',
  full_name='chatservice.ChatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='chatservice.ChatMessage.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recip_username', full_name='chatservice.ChatMessage.recip_username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='chatservice.ChatMessage.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=202,
)


_MESSAGESTATUS = _descriptor.Descriptor(
  name='MessageStatus',
  full_name='chatservice.MessageStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='chatservice.MessageStatus.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=235,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['ListofUsernames'] = _LISTOFUSERNAMES
DESCRIPTOR.message_types_by_name['Wildcard'] = _WILDCARD
DESCRIPTOR.message_types_by_name['ChatMessage'] = _CHATMESSAGE
DESCRIPTOR.message_types_by_name['MessageStatus'] = _MESSAGESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chatservice.Empty)
  })
_sym_db.RegisterMessage(Empty)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chatservice.User)
  })
_sym_db.RegisterMessage(User)

ListofUsernames = _reflection.GeneratedProtocolMessageType('ListofUsernames', (_message.Message,), {
  'DESCRIPTOR' : _LISTOFUSERNAMES,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chatservice.ListofUsernames)
  })
_sym_db.RegisterMessage(ListofUsernames)

Wildcard = _reflection.GeneratedProtocolMessageType('Wildcard', (_message.Message,), {
  'DESCRIPTOR' : _WILDCARD,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chatservice.Wildcard)
  })
_sym_db.RegisterMessage(Wildcard)

ChatMessage = _reflection.GeneratedProtocolMessageType('ChatMessage', (_message.Message,), {
  'DESCRIPTOR' : _CHATMESSAGE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chatservice.ChatMessage)
  })
_sym_db.RegisterMessage(ChatMessage)

MessageStatus = _reflection.GeneratedProtocolMessageType('MessageStatus', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGESTATUS,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chatservice.MessageStatus)
  })
_sym_db.RegisterMessage(MessageStatus)



_CHATSERVER = _descriptor.ServiceDescriptor(
  name='ChatServer',
  full_name='chatservice.ChatServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=238,
  serialized_end=712,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateAccount',
    full_name='chatservice.ChatServer.CreateAccount',
    index=0,
    containing_service=None,
    input_type=_USER,
    output_type=_USER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteAccount',
    full_name='chatservice.ChatServer.DeleteAccount',
    index=1,
    containing_service=None,
    input_type=_USER,
    output_type=_USER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListAccounts',
    full_name='chatservice.ChatServer.ListAccounts',
    index=2,
    containing_service=None,
    input_type=_WILDCARD,
    output_type=_LISTOFUSERNAMES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ChatStream',
    full_name='chatservice.ChatServer.ChatStream',
    index=3,
    containing_service=None,
    input_type=_USER,
    output_type=_CHATMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendMessage',
    full_name='chatservice.ChatServer.SendMessage',
    index=4,
    containing_service=None,
    input_type=_CHATMESSAGE,
    output_type=_MESSAGESTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeliverMessages',
    full_name='chatservice.ChatServer.DeliverMessages',
    index=5,
    containing_service=None,
    input_type=_USER,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Login',
    full_name='chatservice.ChatServer.Login',
    index=6,
    containing_service=None,
    input_type=_USER,
    output_type=_USER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Logout',
    full_name='chatservice.ChatServer.Logout',
    index=7,
    containing_service=None,
    input_type=_USER,
    output_type=_USER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATSERVER)

DESCRIPTOR.services_by_name['ChatServer'] = _CHATSERVER

# @@protoc_insertion_point(module_scope)
