# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x0b\x63hatservice\"\x07\n\x05\x45mpty\"\x18\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\"$\n\x0fListofUsernames\x12\x11\n\tusernames\x18\x01 \x03(\t\"\x1c\n\x08Wildcard\x12\x10\n\x08wildcard\x18\x01 \x01(\t\"H\n\x0b\x43hatMessage\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x16\n\x0erecip_username\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2\xd2\x03\n\nChatServer\x12\x35\n\rCreateAccount\x12\x11.chatservice.User\x1a\x11.chatservice.User\x12\x35\n\rDeleteAccount\x12\x11.chatservice.User\x1a\x11.chatservice.User\x12\x43\n\x0cListAccounts\x12\x15.chatservice.Wildcard\x1a\x1c.chatservice.ListofUsernames\x12;\n\nChatStream\x12\x11.chatservice.User\x1a\x18.chatservice.ChatMessage0\x01\x12;\n\x0bSendMessage\x12\x18.chatservice.ChatMessage\x1a\x12.chatservice.Empty\x12\x38\n\x0f\x44\x65liverMessages\x12\x11.chatservice.User\x1a\x12.chatservice.Empty\x12-\n\x05Login\x12\x11.chatservice.User\x1a\x11.chatservice.User\x12.\n\x06Logout\x12\x11.chatservice.User\x1a\x11.chatservice.Userb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=27
  _EMPTY._serialized_end=34
  _USER._serialized_start=36
  _USER._serialized_end=60
  _LISTOFUSERNAMES._serialized_start=62
  _LISTOFUSERNAMES._serialized_end=98
  _WILDCARD._serialized_start=100
  _WILDCARD._serialized_end=128
  _CHATMESSAGE._serialized_start=130
  _CHATMESSAGE._serialized_end=202
  _CHATSERVER._serialized_start=205
  _CHATSERVER._serialized_end=671
# @@protoc_insertion_point(module_scope)
